apiVersion: apps/v1
kind: Deployment
metadata:
  name: yizijun-site
  labels:
    app: yizijun-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yizijun-site
  template:
    metadata:
      labels:
        app: yizijun-site
    spec:
      containers:
      - name: yizijun-site
        image: gcr.io/civil-pattern-267217/yizijun-site:v1.3.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yizijun-site-service
spec:
  type: NodePort
  selector:
    app: yizijun-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: yizijun-site-certificate
  spec:
    domains:
      - yizijun.site
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: yizijun-site-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 34.102.129.163
    networking.gke.io/managed-certificates: yizijun-site-certificate
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: yizijun-site-service
          servicePort: 80